version: '3.3'

services:
  golang-backend:
    container_name: golang-backend
    build:
      context: ./golang-backend
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
    ports:
      - "3000:3000"

  react-frondend:
    container_name: react-frondend
    build:
      context: ./react-frondend
    ports:
      - "80:80"
    depends_on:
      - golang-backend

